# Secret [ kubernetes secres support only base64 format ]
apiVersion: v1
kind: Secret
metadata:
  name: secret-demo
data:
  # property-like keys; each key maps to a simple value
  dbusername: "db123"
  dbpassword: "dbpswd12"
  token: "gggsydi@12"

--- 
apiVersion: v1
kind: Pod
metadata:
  name: game-pod
spec:
  containers:
    - name: app
      image: docker.io/nginx:latest
      envFrom:
        - secretRef:
            name: secret-demo