# This is like a schedule job and can be trigged as a batch; Whenever it meets the schedule it deploys a job that runs a pod with the mentioned configuration
# As per the schedule, cronJob create a job ----> Job runs the pod ---> Goes to completed state
apiVersion: batch/v1
kind: CronJob
metadata:
  name: hello
spec:
  schedule: "*/2 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: hello
            image: busybox:1.28
            imagePullPolicy: IfNotPresent
            command:
            - /bin/sh
            - -c
            - date; echo Hello from the Kubernetes cluster
          restartPolicy: OnFailure