# creates service account
apiVersion: v1
kind: ServiceAccount
metadata:
  name: expense 
--- 
# Create a role in default namespace
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: default
  name: ns-read-only
rules:
- apiGroups: [""] # "" indicates the core API group
  resources: ["pods"]
  verbs: ["get", "list"]
