# Vertical Pod Autosclaing### HPA : Horizonal Pod Autoscaling
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: my-app
        image: docker.io/nginx:latest
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "100Mi"
            cpu: "50m"
          limits:
            memory: "150Mi"
            cpu: "100m"

--- 
# Provisions VPA 
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: frontend-vpa
spec:
  targetRef:
    apiVersion: "apps/v1"
    kind: Deployment
    name: frontend 
  updatePolicy: 
    updateMode: "Auto"
  resourcePolicy:
    containerPolicies:
      - containerName: '*'
        minAllowed:
          cpu: 100m
          memory: 50Mi
        maxAllowed:
          cpu: 1
          memory: 500Mi
        controlledResources: ["cpu", "memory"]
# --- 

# apiVersion: "autoscaling.k8s.io/v1"
# kind: VerticalPodAutoscaler
# metadata:
#   name: hamster-vpa
# spec:
#   targetRef:
#     apiVersion: "apps/v1"
#     kind: Deployment
#     name: hamster
#   resourcePolicy:
#     containerPolicies:
#       - containerName: '*'
#         minAllowed:
#           cpu: 100m
#           memory: 50Mi
#         maxAllowed:
#           cpu: 1
#           memory: 500Mi
#         controlledResources: ["cpu", "memory"]